# 1. Ensure that your repository contains the necessary configuration
#    Google Kubernetes Engine cluster,including deployment.yml, kustomization.yml, service.yml, etc.

# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, REGISTRY_HOSTNAME and DEPLOYMENT_NAME environment variables (below).

# TODO
# 1. setup kustomization
# 2. create k8s env namespace (mach kustomization), in here is 'staging' and 'production'
# 3. finish the env variable

# prettier-ignore
name: Firstory release deploy

on:
  release:    
    types: [published]

env:    
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: asia-east1-a
  GKE_CLUSTER: graphql-prisma-asia 
  IMAGE: graphql
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: graphql

jobs:
  DeployStaging:
    - name: Deploy to staging
      run: echo "github.ref is $github.ref"
